In [2]:
import torch

if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

We have a GPU!


In [3]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

tensor([[0.2706, 0.1161],
        [0.0755, 0.7742]], device='cuda:0')


In [5]:
torch.cuda.device_count()
if torch.cuda.is_available():
    my_device = torch.device('cuda')
else:
    my_device = torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cuda
tensor([[0.0874, 0.1246],
        [0.0615, 0.2122]], device='cuda:0')


In [14]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
z = x + y # exception will be thrown
torch.device

torch.device

In [15]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [18]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

c, d

torch.Size([1, 20])
tensor([[0.5614, 0.2552, 0.1578, 0.5566, 0.5615, 0.0013, 0.3682, 0.0994, 0.9138,
         0.6367, 0.0158, 0.2830, 0.9107, 0.1848, 0.0411, 0.1980, 0.5434, 0.9867,
         0.1351, 0.8567]])
torch.Size([20])
tensor([0.5614, 0.2552, 0.1578, 0.5566, 0.5615, 0.0013, 0.3682, 0.0994, 0.9138,
        0.6367, 0.0158, 0.2830, 0.9107, 0.1848, 0.0411, 0.1980, 0.5434, 0.9867,
        0.1351, 0.8567])
torch.Size([2, 2])
torch.Size([2, 2])


(tensor([[0.5056, 0.4536],
         [0.8998, 0.8357]]),
 tensor([[0.5056, 0.4536],
         [0.8998, 0.8357]]))

In [10]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!
a, b

torch.Size([3, 1])
tensor([[[0.8550, 0.8550],
         [0.6534, 0.6534],
         [0.1569, 0.1569]],

        [[0.8550, 0.8550],
         [0.6534, 0.6534],
         [0.1569, 0.1569]],

        [[0.8550, 0.8550],
         [0.6534, 0.6534],
         [0.1569, 0.1569]],

        [[0.8550, 0.8550],
         [0.6534, 0.6534],
         [0.1569, 0.1569]]])


(tensor([[[1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.]]]),
 tensor([0.8550, 0.6534, 0.1569]))

In [19]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c), old_id    # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c), old_id    # still the same object!


tensor([[0., 0.],
        [0., 0.]])
tensor([[0.0838, 0.4356],
        [0.2784, 0.3154]])
tensor([[0.3075, 0.8314],
        [0.4360, 0.1640]])


In [23]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
z, loss

(tensor([ 4.7513,  1.6770, -3.1417], grad_fn=<AddBackward0>),
 tensor(2.2169, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>))