In [14]:
import torch

x = torch.arange(4, dtype=torch.float32, requires_grad=True)
y = 2 * torch.dot(x, x)
y.backward()
print(x.grad)

#清除梯度
x.grad.zero_()
print(x.grad)

y = x.sum()
y.backward()
print(x.grad)

#detach方法固定参数
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad, u

tensor([ 0.,  4.,  8., 12.])
tensor([0., 0., 0., 0.])
tensor([1., 1., 1., 1.])


(tensor([0., 1., 4., 9.]), tensor([0., 1., 4., 9.]))