In [83]:
import torch

a = torch.arange(24, dtype = torch.float32).reshape(2, 3, 4)
b = torch.arange(6, dtype = torch.float32).reshape(1, 2, 3)
c = a.clone()

#print(a, '\n', a.sum(), '\n', a.sum(axis = 0), '\n', a.sum(axis = 1), '\n', a.sum(axis = 2))
#print(a.mean(),'\n', a.mean(axis =0), '\n', a.mean(axis =1), '\n', a.mean(axis =2))
#print(a.size() == a.shape)
#print(a.mean(axis =1, keepdims = True),a.mean(axis =1))
#a, a.cumsum(axis = 1)
a0 = torch.ones(4)
b0 = torch.ones_like(a0)
print(torch.dot(a0, b0))

A = torch.ones(3, 4)
B = torch.ones(4, 5)
print(torch.mv(A, a0))
print(torch.mm(A, B))

print(torch.norm(A)) #F范数
print(a, a.sum(axis = [0, 1]))

tensor(4.)
tensor([4., 4., 4.])
tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])
tensor(3.4641)
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]]) tensor([60., 66., 72., 78.])
